# Generated by Django 3.2.2 on 2021-06-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hocphan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hocphan',
            fields=[
                ('mahp', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('tenhp', models.CharField(max_length=50)),
                ('sotinchi', models.IntegerField(default=1)),
                ('loaihp', models.CharField(choices=[('Lý thuyết', 'Lý thuyết'), ('Thực hành', 'Thực hành')], default='Lý thuyết', max_length=20)),
                ('mahk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocphan.hocky')),
            ],
        ),
    ]
