# Generated by Django 3.2.2 on 2021-06-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hocphan', '0003_thamgiahocphan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hocky',
            old_name='tenhp',
            new_name='tenhk',
        ),
    ]
