# Generated by Django 3.2.2 on 2021-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hocphan', '0004_rename_tenhp_hocky_tenhk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thamgiahocphan',
            name='ngaykt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
