# Generated by Django 3.2.2 on 2021-06-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dienchinhsach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienchinhsach',
            name='tilegiamhocphi',
            field=models.FloatField(default=0),
        ),
    ]
