# Generated by Django 3.2.2 on 2021-06-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dienchinhsach', '0002_alter_dienchinhsach_tilegiamhocphi'),
        ('khoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=50)),
                ('ngaysinh', models.DateField()),
                ('phai', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=3)),
                ('quequan', models.CharField(max_length=255)),
                ('madcs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienchinhsach.dienchinhsach')),
                ('makhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoa.khoa')),
            ],
        ),
    ]
