# Generated by Django 3.2.2 on 2021-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysinhvien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien',
            name='id',
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='masv',
            field=models.CharField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
    ]
