# Generated by Django 3.2.2 on 2021-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysinhvien', '0002_auto_20210617_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='masv',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False),
        ),
    ]
