# Generated by Django 3.2.2 on 2021-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysinhvien', '0004_auto_20210617_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='tensv',
            field=models.CharField(max_length=500),
        ),
    ]
