# Generated by Django 3.2.2 on 2021-06-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlysinhvien', '0005_alter_sinhvien_tensv'),
    ]

    operations = [
        migrations.CreateModel(
            name='quequan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenqq', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='quequan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlysinhvien.quequan'),
        ),
    ]
